### ISSUE TITLE
Describe the purpose of the library

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/CUDA-wrappers#12]
In README.md we should explain what problem this library solves.

**Comment by john-romein** [comment]
The main purposes are: _easier resource management_, leading to _lower risk of programming errors_; _better fault handling_ (through exceptions); _more compact user code_.  Originally, the API enforced RAII to even further reduce the risk of faulty code, but enforcing RAII and compatibility with (unmanaged) objects obtained outside this API are mutually exclusive.

**Comment by svlugt** [comment]
This library is a C++ wrapper for the Nvidia C libraries (e.g. CUDA driver, nvrtc, cuFFT etc.) 
+ above mentioned main purposes.

**Comment by jspaaks** [comment]
PR was merged, closing this issue
