### ISSUE TITLE
Add contributer guidelines

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/CUDA-wrappers#18]
add CONTRIBUTING.md

CONTRIBUTING.md from `python-template` can be reused but needs some changes.
https://github.com/NLeSC/python-template/blob/a59600f328d0eadad548893ac4822f37e54b677e/%7B%7Bcookiecutter.directory_name%7D%7D/CONTRIBUTING.md

**Comment by abelsiqueira** [comment]
PR merged. Closing.
