### ISSUE TITLE
add an issue template

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/CUDA-wrappers#19]

**Comment by jspaaks** [comment]
We have a PR template but not an issue template. We could close this issue or rename to _Add an issue template_ (if we know what issue template we need)

ping @fdiblen

**Comment by jspaaks** [comment]
> if we know what issue template we need)

What issue template were you thinking of adding @fdiblen ?

**Comment by fdiblen** [comment]
Fixed by #69
