### ISSUE TITLE
Add CII badge

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/CUDA-wrappers#22]
Alternatives:
- https://www.coreinfrastructure.org/programs/best-practices-program/

**Comment by jspaaks** [comment]
Example of checklist report https://bestpractices.coreinfrastructure.org/en/projects/1811

**Comment by fdiblen** [comment]
We decided to add a CII badge to the code.

**Comment by jspaaks** [comment]
https://bestpractices.coreinfrastructure.org/en/projects/5686

**Comment by jspaaks** [comment]
PR was merged, closing
