### ISSUE TITLE
Use a static code analysis tool

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/CUDA-wrappers#23]
We need a tool that can analyse the code and generate a report.
https://sonarcloud.io/ can be one of the options.

Ask @benvanwerkhoven and @isazi for suggestions.

**Comment by isazi** [comment]
Sonarcloud supports C/C++ applications, not sure about CUDA.

**Comment by benvanwerkhoven** [comment]
Yeah I have reasonably good experience using sonarcloud on the Kernel Tuner repository. The only issue I have is that it complains about using pseudo-random numbers being insecure, while I use those for stochastic optimization in a context unrelated to security. But after many attempts I seem to have been able to disable most of those checks now, I think.

**Comment by isazi** [comment]
And I believe it is possible to disable checks in the libraries.

**Comment by jspaaks** [comment]
It seems everybody is on board with SonarCloud. @fdiblen I suggest updating the issue title to _Set up sonarcloud_ so this issue becomes more actionable.

**Comment by bouweandela** [comment]
Is it possible to run the Sonarcloud linter(s) locally, e.g. from a pre-commit hook? Or is it a proprietary linter?

**Comment by bouweandela** [comment]
Maybe this list could also be used for inspiration? https://github.com/caramelomartins/awesome-linters#cc

**Comment by bouweandela** [comment]
Related discussion in #26

**Comment by abelsiqueira** [comment]
I had issues installing SonarCloud, but it looks like it is working now.

Looks like @loostrum made a request to enable it for the organization in the past, and it conflicted with my request. Since there were no projects already using it for this organization, I uninstalled it and started from scratch. @loostrum, I have not enabled it for your repo, but it should be possible to do it now.

**Comment by bouweandela** [comment]
@csbnw mentioned that at Astron they make use of:
- C++ code: `clang-format` and `clang-tidy` with [Google code style](https://google.github.io/styleguide/cppguide.html) 
- Cmake files: [`cmake-format` and `cmake-lint`](https://cmake-format.readthedocs.io/en/latest/)

**Comment by fdiblen** [comment]
We will look into codacy as it seems to be supporting the tools we use locally. See https://docs.codacy.com/getting-started/supported-languages-and-tools/

**Comment by abelsiqueira** [comment]
PR merged.
