### ISSUE TITLE
Scope of the CHANGELOG

### ISSUE THREAD

**Issue by jspaaks** [nlesc-recruit/CUDA-wrappers#67]
PR #60 spawned some discussion about what to include in the CHANGELOG.md. For example, we could choose to include anything that changes in the repo, or only the subset that affects users, for example if there are breaking changes, or a new feature, or something else that will be reflected in the semver.

**Comment by fdiblen** [comment]
@john-romein Do you think the CHANGELOG is helpful?

**Comment by john-romein** [comment]
CHANCELOG.md should include the changes that affects users (such as API changes or change in behavior), but not minor implementation changes.

**Comment by fdiblen** [comment]
Thank you @john-romein. We will keep the changelog as you described.
