### ISSUE TITLE
Reorganize the folders and the source files

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/CUDA-wrappers#9]
use correct file extensions: cpp, hpp
use include and src folder instead of cu
add example to `tests` folder

**Comment by jspaaks** [comment]
Something like this:
```plain
.
├── cudawrappers
│   ├── CMakeLists.txt
│   ├── cudawrappers-config.cmake
│   ├── include
│   │   └── cudawrappers.hpp
│   ├── README.md
│   ├── src
│   │   └── cudawrappers.cpp
│   └── tests
│       ├── CMakeLists.txt
│       ├── convolution
│       │   ├── convolution.cpp
│       │   └── README.md
│       ├── README.md
│       └── vector_add
│           ├── README.md
│           ├── vector_add.cpp
│           └── vector_add.cu
└── cudawrappers-usage-examples
    ├── cmake-pull
    │   ├── CMakeLists.txt
    │   └── helloworld.cpp
    ├── git-submodule
    │   ├── cudawrappers@0.1.0
    │   └── helloworld.cpp
    ├── locally-installed
    │   ├── CMakeLists.txt
    │   └── helloworld.cpp
    ├── plain-copy
    │   ├── CMakeLists.txt
    │   ├── cudawrappers
    │   └── helloworld.cpp
    └── README.md
```

`cudawrappers-usage-examples` will be a separate repository

**Comment by jspaaks** [comment]
Maybe use sagecal for inspiration on CMakeLists configuration

e.g. https://github.com/nlesc-dirac/sagecal/blob/master/CMakeLists.txt

**Comment by fdiblen** [comment]
Suggestion from Abel: We should also add examples to the cudawrappers repo.

**Comment by fdiblen** [comment]
@benvanwerkhoven @isazi @bouweandela What do you think about the proposed folder structure?

**Comment by bouweandela** [comment]
@fdiblen Looks good to me, except that I'm not super happy with the README.md files buried in the directory tree: this makes information hard to find. Why not have all info in the README.md at the top level or on a documentation webpage?

It would also be good to hear the opinion of our project partners @john-romein @csbnw and @svlugt on this. Does this work for you?

**Comment by jspaaks** [comment]
PR #43 was merged, I think we can close this issue. If we feel Bouwe's comment about READMEs above should be addressed, we should make a separate issue for it.

ping @fdiblen
